timeout: 5
default_entry: HXNU

/HXNU
    comment: HXNU Micro-Hybrid Kernel v2608 - Neonix OS (BerryComp Labs)
    protocol: limine
    path: boot():/boot/kernel
    module_path: boot():/boot/initrd.cpio
    module_string: initrd
