use std::env;
use std::fs;
use std::path::PathBuf;

const DEFAULT_PROFILE: &str = "minimal-v1";
const DEFAULT_OUT: &str = "kernel/src/mm/compress/profile_generated.rs";

fn main() {
    if let Err(error) = run() {
        eprintln!("sxrc-profile-gen: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let config = parse_args(env::args().skip(1))?;
    let generated = render_profile(&config.profile)?;

    if let Some(parent) = config.out.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create output directory {}: {error}", parent.display()))?;
    }
    fs::write(&config.out, generated)
        .map_err(|error| format!("failed to write {}: {error}", config.out.display()))?;

    println!(
        "generated {} with profile {}",
        config.out.display(),
        config.profile
    );
    Ok(())
}

struct Config {
    profile: String,
    out: PathBuf,
}

fn parse_args<I>(args: I) -> Result<Config, String>
where
    I: IntoIterator<Item = String>,
{
    let mut profile = String::from(DEFAULT_PROFILE);
    let mut out = PathBuf::from(DEFAULT_OUT);
    let mut iter = args.into_iter();

    while let Some(arg) = iter.next() {
        match arg.as_str() {
            "--profile" => {
                profile = iter
                    .next()
                    .ok_or_else(|| String::from("missing value for --profile"))?;
            }
            "--out" => {
                out = PathBuf::from(
                    iter.next()
                        .ok_or_else(|| String::from("missing value for --out"))?,
                );
            }
            "-h" | "--help" => {
                print_help();
                std::process::exit(0);
            }
            other => {
                return Err(format!("unknown argument: {other}"));
            }
        }
    }

    Ok(Config { profile, out })
}

fn print_help() {
    println!("sxrc-profile-gen [--profile <name>] [--out <path>]");
    println!("  --profile  profile name (default: {DEFAULT_PROFILE})");
    println!("  --out      output Rust file (default: {DEFAULT_OUT})");
}

fn render_profile(profile: &str) -> Result<String, String> {
    match profile {
        "minimal-v1" => Ok(String::from(
            "// AUTO-GENERATED BY tools/sxrc-profile-gen.\n// DO NOT EDIT MANUALLY.\n\npub const HXNU_SXRC_PROFILE_NAME: &str = \"minimal-v1\";\npub const HXNU_SXRC_PROFILE_VERSION: u32 = 1;\npub const HXNU_SXRC_PAGE_SIZE: usize = 4096;\npub const HXNU_SXRC_COMPRESSION_UNIT_BYTES: usize = 2;\npub const HXNU_SXRC_ENDIAN_LITTLE: bool = true;\npub const HXNU_SXRC_ENABLE_DYNAMIC_PATTERNS: bool = false;\n\npub const HXNU_SXRC_STATIC_DICTIONARY: &[(u16, u32)] = &[\n    (0x0001, 0x0000_0000),\n    (0x0002, 0x0000_ffff),\n    (0x0003, 0x0000_07fe),\n    (0x0004, 0x0000_04ee),\n    (0x0005, 0x0000_9090),\n];\n\npub const HXNU_SXRC_STATIC_PATTERNS: &[(u16, &[u8])] = &[\n    (0x0001, b\"\\x48\\x89\\xd8\"),\n    (0x0002, b\"\\x55\"),\n];\n",
        )),
        other => Err(format!("unsupported profile: {other}")),
    }
}
