[package]
name = "hxnu-kernel"
version = "2608.0.0-rc.1"
edition = "2024"
publish = false

[features]
default = []
exception-test-breakpoint = []
exception-test-page-fault = []
exception-test-general-protection = []
panic-self-test = []
power-reset-self-test = []
heterexec-self-test = []

[dependencies]
hps = { package = "heterexec", path = "../../heterexec" }
