// AUTO-GENERATED BY tools/sxrc-profile-gen.
// DO NOT EDIT MANUALLY.

pub const HXNU_SXRC_PROFILE_NAME: &str = "minimal-v1";
pub const HXNU_SXRC_PROFILE_VERSION: u32 = 1;
pub const HXNU_SXRC_PAGE_SIZE: usize = 4096;
pub const HXNU_SXRC_COMPRESSION_UNIT_BYTES: usize = 2;
pub const HXNU_SXRC_ENDIAN_LITTLE: bool = true;
pub const HXNU_SXRC_ENABLE_DYNAMIC_PATTERNS: bool = false;

pub const HXNU_SXRC_STATIC_DICTIONARY: &[(u16, u32)] = &[
    (0x0001, 0x0000_0000),
    (0x0002, 0x0000_ffff),
    (0x0003, 0x0000_07fe),
    (0x0004, 0x0000_04ee),
    (0x0005, 0x0000_9090),
];

pub const HXNU_SXRC_STATIC_PATTERNS: &[(u16, &[u8])] = &[
    (0x0001, b"\x48\x89\xd8"),
    (0x0002, b"\x55"),
];
